docs_dir: doc/book
site_dir: doc/html
pages:
    - index.md
    - Introduction: intro.md
    - Reference:
        - "Response Types": response.md
        - "Error Handling Middleware": middleware.md
        - "Exceptions": exception.md
site_name: Problem Details
site_description: 'Problem Details for PSR-7 Applications'
repo_url: 'https://github.com/weierophinney/problem-details'
copyright: 'Copyright (c) 2017 <a href="https://mwop.net/">Matthew Weier O\'Phinney</a>'
extra_css:
    - css/zend-expressive.css
